openapi: 3.0.0
info:
  title: Authentication API
  version: 3.0.0
tags:
  - name: Auth
    description: Authentication API
paths:
  /api/v1/auth/login:
    post:
      summary: Login a user
      description: Login a user
      operationId: login
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: true
              $ref: '#/components/schemas/LoginDto'
      responses:
        '200':
          description: a user object
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /api/v1/auth/signup:
    post:
      summary: Signup a user
      description: Signup a user
      operationId: signup
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: true
              $ref: '#/components/schemas/SignupDto'
      responses:
        '201':
          description: a user object
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /api/v1/auth/logout:
    post:
      summary: Logout a user
      description: Logout a user
      operationId: logout
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: a user object
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /api/v1/auth/forgot-password:
    post:
      summary: Forgot password
      description: Forgot password
      operationId: forgotPassword
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: true
              $ref: '#/components/schemas/ForgotPasswordDto'
      responses:
        '200':
          description: a user object
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /api/v1/auth/reset-password/{resetToken}:
    post:
      summary: Reset password
      description: Reset password
      operationId: resetPassword
      tags:
        - Auth
      parameters:
        - in: path
          name: resetToken
          required: true
          schema:
            type: string
          description: Reset token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: true
              $ref: '#/components/schemas/ResetPasswordDto'
      responses:
        '200':
          description: a user object
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /api/v1/auth/update-my-password:
    post:
      summary: Update my password
      description: update my password route for logged in users to update their own password
      operationId: updateMyPassword
      tags:
        - Auth
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: true
              $ref: '#/components/schemas/UpdatePasswordDto'
      responses:
        '200':
          description: a user object
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginDto:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    SignupDto:
      type: object
      required:
        - username
        - email
        - password
        - passwordConfirm
        - phoneNumber
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        passwordConfirm:
          type: string
        phoneNumber:
          type: string
    ForgotPasswordDto:
      type: object
      required:
        - email
      properties:
        email:
          type: string
    ResetPasswordDto:
      type: object
      required:
        - password
        - passwordConfirm
      properties:
        password:
          type: string
        passwordConfirm:
          type: string
    UpdatePasswordDto:
      type: object
      required:
        - currentPassword
        - newPassword
        - passwordConfirm
      properties:
        currentPassword:
          type: string
        newPassword:
          type: string
        passwordConfirm:
          type: string
