openapi: 3.0.0
info:
  title: Rooms API
  version: 3.0.0
tags:
  - name: Rooms
    description: Rooms API
paths:
  /api/v1/rooms:
    get:
      summary: Get all rooms
      description: Get all rooms
      operationId: getAllRooms
      tags:
        - Rooms
      responses:
        '200':
          description: an object with pagination and list of rooms
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  results:
                    type: number
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/IRoomResponse'
        '500':
          description: Internal server error'
    post:
      summary: Create a room
      description: Create a room
      operationId: createRoom
      tags:
        - Rooms
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRoomDto'
      responses:
        '201':
          description: a room object
        '400':
          description: Invalid input
        '500':
          description: Internal server error
  /api/v1/rooms/{id}:
    get:
      summary: Get a room by id
      description: Get a room by id
      operationId: getRoomById
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the room to get
          schema:
            type: string
      tags:
        - Rooms
      responses:
        '200':
          description: a room object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IRoomResponse'
        '404':
          description: Room not found
        '500':
          description: Internal server error
    patch:
      summary: Update a room by id
      description: Update a room by id
      operationId: updateRoomById
      tags:
        - Rooms
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the room to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateRoomDto'
      responses:
        '200':
          description: a room object
        '400':
          description: Invalid input
        '404':
          description: Room not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a room by id
      description: Delete a room by id
      operationId: deleteRoomById
      tags:
        - Rooms
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the room to delete
          schema:
            type: string
      responses:
        '204':
          description: Room deleted
        '404':
          description: Room not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    IRoomResponse:
      type: object
      properties:
        _id:
          type: string
        hotel:
          type: string
        roomFacilities:
          type: array
          items:
            type: string
        capacity:
          type: number
        description:
          type: string
        pricePerNight:
          type: number
        images:
          type: array
          items:
            type: string
        roomType:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CreateRoomDto:
      type: object
      required:
        - hotel
        - roomFacilities
        - capacity
        - description
        - pricePerNight
        - images
        - roomType
        - roomNumber
      properties:
        hotel:
          type: string
        roomType:
          type: string
        roomNumber:
          type: number
        roomFacilities:
          type: array
          items:
            type: string
        capacity:
          type: number
        description:
          type: string
        pricePerNight:
          type: number
        images:
          type: array
          items:
            type: string
            format: binary
            minimum: 1
            maximum: 5
            description: Image Cover for a room at least one image is required
    UpdateRoomDto:
      type: object
      properties:
        roomType:
          type: string
        roomNumber:
          type: number
        roomFacilities:
          type: array
          items:
            type: string
        capacity:
          type: number
        description:
          type: string
        pricePerNight:
          type: number
        images:
          type: array
          items:
            type: string
            format: binary
            minimum: 1
            maximum: 5
            description: Image Cover for a room at least one image is required
